version: '2'
services:
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
      - ./var:/app/var
    ports:
      - "8000:8000"
